# Generated by Django 4.1.3 on 2023-09-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'USER'), (2, 'BOT')]),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'TEXT'), (2, 'AUDIO')]),
        ),
    ]
