# Generated by Django 4.1.3 on 2023-10-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_conversation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
